# RLM Session Start Hook (Claude Code)
# Logs session start and loads RLM pipeline state
# Claude Code stdin JSON: { session_id, cwd, hook_event_name }

$ErrorActionPreference = "Stop"

try {
    $input = [Console]::In.ReadToEnd() | ConvertFrom-Json
    $sessionId = if ($input.PSObject.Properties['session_id']) { $input.session_id } else { "" }
    $cwd = if ($input.PSObject.Properties['cwd']) { $input.cwd } else { $env:CLAUDE_PROJECT_DIR }

    if (-not $cwd) { $cwd = "." }

    # Ensure logs directory exists
    $logDir = Join-Path $cwd "RLM" "progress" "logs"
    if (-not (Test-Path $logDir)) {
        New-Item -ItemType Directory -Force -Path $logDir | Out-Null
    }

    $now = Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ'

    # Backward-compatible log
    $logFile = Join-Path $logDir "sessions.log"
    $entry = "$now | START | source=claude-code"
    Add-Content -Path $logFile -Value $entry

    # Check for existing pipeline state
    $pipelinePhase = $null
    $stateFile = Join-Path $cwd "RLM" "progress" "pipeline-state.json"
    if (Test-Path $stateFile) {
        $state = Get-Content $stateFile -Raw | ConvertFrom-Json
        $pipelinePhase = $state.current_phase
        Add-Content -Path $logFile -Value "$now | INFO  | Resuming pipeline at phase $pipelinePhase"
    }

    # Structured JSONL log
    $jsonlFile = Join-Path $logDir "sessions.jsonl"
    $jsonEntry = @{
        timestamp = $now
        event = "session.start"
        source = "claude-code"
        sessionId = $sessionId
    }
    if ($null -ne $pipelinePhase) {
        $jsonEntry.pipelinePhase = $pipelinePhase
    }
    $jsonEntry | ConvertTo-Json -Compress | Add-Content -Path $jsonlFile

    # Generate .current-context.md for dynamic context injection
    # (simulates Copilot's prompt.pre hook — injects pipeline state per session)
    $contextFile = Join-Path $cwd "RLM" "progress" ".current-context.md"
    $progressDir = Join-Path $cwd "RLM" "progress"
    if (-not (Test-Path $progressDir)) {
        New-Item -ItemType Directory -Force -Path $progressDir | Out-Null
    }

    $currentAgent = $null
    $automationLevel = "SUPERVISED"
    $lastTask = $null

    if (Test-Path $stateFile) {
        if ($state.PSObject.Properties['current_agent']) { $currentAgent = $state.current_agent }
        if ($state.PSObject.Properties['automation_level']) { $automationLevel = $state.automation_level }
    }

    $statusFile = Join-Path $cwd "RLM" "progress" "status.json"
    if (Test-Path $statusFile) {
        $status = Get-Content $statusFile -Raw | ConvertFrom-Json
        if ($status.PSObject.Properties['inProgress']) { $lastTask = $status.inProgress }
        elseif ($status.PSObject.Properties['currentTask']) { $lastTask = $status.currentTask }
    }

    $contextLines = @(
        "# Active RLM Pipeline Context"
        ""
        "> Auto-generated by session-start hook at $now. Do not edit manually."
        ""
    )
    if ($null -ne $pipelinePhase) {
        $contextLines += "- **Pipeline Phase**: $pipelinePhase"
    } else {
        $contextLines += "- **Pipeline Phase**: Not started"
    }
    if ($currentAgent) {
        $contextLines += "- **Current Agent**: $currentAgent"
    }
    if ($lastTask) {
        $contextLines += "- **Active Task**: $lastTask"
    }
    $contextLines += "- **Automation Level**: $automationLevel"
    $contextLines += "- **Session Started**: $now"
    $contextLines += ""

    # Include last session info from checkpoint
    $checkpointFile = Join-Path $cwd "RLM" "progress" "checkpoint.json"
    if (Test-Path $checkpointFile) {
        $checkpoint = Get-Content $checkpointFile -Raw | ConvertFrom-Json
        if ($checkpoint.PSObject.Properties['lastSession'] -and $checkpoint.lastSession.PSObject.Properties['endedAt']) {
            $contextLines += "- **Previous Session Ended**: $($checkpoint.lastSession.endedAt)"
        }
    }

    # --- Sandbox Detection ---
    $sandboxMode = $false
    $sandboxId = $null
    $configFile = Join-Path $cwd "RLM" "progress" "config.json"
    if (Test-Path $configFile) {
        $config = Get-Content $configFile -Raw | ConvertFrom-Json
        if ($config.PSObject.Properties['sandbox'] -and $config.sandbox.PSObject.Properties['enabled']) {
            $sandboxMode = $config.sandbox.enabled
        }
    }
    $sandboxStateFile = Join-Path $cwd "sandbox" ".sandbox-state.json"
    if (Test-Path $sandboxStateFile) {
        $sbxState = Get-Content $sandboxStateFile -Raw | ConvertFrom-Json
        if ($sbxState.PSObject.Properties['sandbox_id']) { $sandboxId = $sbxState.sandbox_id }
    }

    if ($sandboxMode) {
        $contextLines += "- **Sandbox Mode**: active"
        if ($sandboxId) { $contextLines += "- **Sandbox ID**: $sandboxId" }
        $contextLines += "- **Sandbox Skill**: sandbox/SKILL.md"
    }

    $contextLines -join "`n" | Set-Content -Path $contextFile -NoNewline

    exit 0
} catch {
    # Hooks should not block the session
    exit 0
}
