#!/bin/bash
# RLM Session Start Hook (Claude Code) — logs session start and loads pipeline state
# Claude Code stdin JSON: { session_id, cwd, hook_event_name }
INPUT=$(cat)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
CWD=$(echo "$INPUT" | jq -r '.cwd // empty')

# Fallback to CLAUDE_PROJECT_DIR if cwd not in input
if [ -z "$CWD" ]; then
  CWD="${CLAUDE_PROJECT_DIR:-.}"
fi

LOG_DIR="$CWD/RLM/progress/logs"
mkdir -p "$LOG_DIR"

NOW=$(date -Iseconds 2>/dev/null || date +%Y-%m-%dT%H:%M:%S%z)

# Backward-compatible log
echo "$NOW | START | source=claude-code" >> "$LOG_DIR/sessions.log"

# Check for existing pipeline state
PHASE=""
STATE_FILE="$CWD/RLM/progress/pipeline-state.json"
if [ -f "$STATE_FILE" ]; then
  PHASE=$(jq -r '.current_phase // empty' "$STATE_FILE" 2>/dev/null)
  echo "$NOW | INFO  | Resuming pipeline at phase $PHASE" >> "$LOG_DIR/sessions.log"
fi

# Structured JSONL log
JSONL_ENTRY=$(jq -n --arg ts "$NOW" --arg src "claude-code" --arg sid "$SESSION_ID" --arg ph "$PHASE" \
  '{timestamp:$ts, event:"session.start", source:$src, sessionId:$sid} + (if $ph != "" then {pipelinePhase:($ph | tonumber? // $ph)} else {} end)')
echo "$JSONL_ENTRY" >> "$LOG_DIR/sessions.jsonl"

# Generate .current-context.md for dynamic context injection (simulates Copilot's prompt.pre hook)
CONTEXT_FILE="$CWD/RLM/progress/.current-context.md"
AGENT=""
AUTOMATION=""
LAST_TASK=""

if [ -f "$STATE_FILE" ]; then
  AGENT=$(jq -r '.current_agent // empty' "$STATE_FILE" 2>/dev/null)
  AUTOMATION=$(jq -r '.automation_level // "SUPERVISED"' "$STATE_FILE" 2>/dev/null)
fi

STATUS_FILE="$CWD/RLM/progress/status.json"
if [ -f "$STATUS_FILE" ]; then
  LAST_TASK=$(jq -r '.inProgress // .currentTask // empty' "$STATUS_FILE" 2>/dev/null)
fi

{
  echo "# Active RLM Pipeline Context"
  echo ""
  echo "> Auto-generated by session-start hook at $NOW. Do not edit manually."
  echo ""
  if [ -n "$PHASE" ]; then
    echo "- **Pipeline Phase**: $PHASE"
  else
    echo "- **Pipeline Phase**: Not started"
  fi
  if [ -n "$AGENT" ]; then
    echo "- **Current Agent**: $AGENT"
  fi
  if [ -n "$LAST_TASK" ]; then
    echo "- **Active Task**: $LAST_TASK"
  fi
  echo "- **Automation Level**: ${AUTOMATION:-SUPERVISED}"
  echo "- **Session Started**: $NOW"
  echo ""
  # Include last session info from checkpoint
  CHECKPOINT="$CWD/RLM/progress/checkpoint.json"
  if [ -f "$CHECKPOINT" ]; then
    LAST_ENDED=$(jq -r '.lastSession.endedAt // empty' "$CHECKPOINT" 2>/dev/null)
    if [ -n "$LAST_ENDED" ]; then
      echo "- **Previous Session Ended**: $LAST_ENDED"
    fi
  fi
  # --- Sandbox Detection ---
  SANDBOX_MODE="false"
  SANDBOX_ID=""
  CONFIG_FILE="$CWD/RLM/progress/config.json"
  if [ -f "$CONFIG_FILE" ]; then
    SANDBOX_ENABLED=$(jq -r '.sandbox.enabled // false' "$CONFIG_FILE" 2>/dev/null)
    if [ "$SANDBOX_ENABLED" = "true" ]; then
      SANDBOX_MODE="true"
    fi
  fi
  SANDBOX_STATE_FILE="$CWD/sandbox/.sandbox-state.json"
  if [ -f "$SANDBOX_STATE_FILE" ]; then
    SANDBOX_ID=$(jq -r '.sandbox_id // empty' "$SANDBOX_STATE_FILE" 2>/dev/null)
  fi
  if [ "$SANDBOX_MODE" = "true" ]; then
    echo "- **Sandbox Mode**: active"
    if [ -n "$SANDBOX_ID" ]; then
      echo "- **Sandbox ID**: $SANDBOX_ID"
    fi
    echo "- **Sandbox Skill**: sandbox/SKILL.md"
  fi
} > "$CONTEXT_FILE"

# Write session-specific context file for isolation
SESSION_CONTEXT_DIR="$CWD/RLM/progress/.session-contexts"
mkdir -p "$SESSION_CONTEXT_DIR"

if [ -n "$SESSION_ID" ]; then
  cp "$CONTEXT_FILE" "$SESSION_CONTEXT_DIR/session-$SESSION_ID.md"
fi

exit 0
