# RLM Alias Installer for PowerShell
# Adds 'rlm' function to PowerShell profile for quick orchestrator access

$ErrorActionPreference = "Stop"

Write-Host "`n🚀 RLM Alias Installer for PowerShell`n" -ForegroundColor Cyan

# Detect PowerShell profile path
$profilePath = $PROFILE.CurrentUserAllHosts
Write-Host "📁 Profile path: $profilePath" -ForegroundColor Gray

# Get current directory to embed in function
$currentDir = Get-Location

# Backup existing profile
if (Test-Path $profilePath) {
    $backupPath = "$profilePath.backup-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
    Copy-Item $profilePath $backupPath
    Write-Host "✅ Backed up profile to: $backupPath" -ForegroundColor Green
} else {
    Write-Host "📝 Profile doesn't exist yet. Will create new one." -ForegroundColor Gray
}

# Create profile directory if doesn't exist
$profileDir = Split-Path -Parent $profilePath
if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    Write-Host "✅ Created profile directory: $profileDir" -ForegroundColor Green
}

# Create profile if doesn't exist
if (-not (Test-Path $profilePath)) {
    New-Item -ItemType File -Path $profilePath -Force | Out-Null
}

# Check if alias already exists
$profileContent = Get-Content $profilePath -Raw -ErrorAction SilentlyContinue
if ($profileContent -match "function rlm") {
    Write-Host "`n⚠️  'rlm' function already exists in profile!" -ForegroundColor Yellow
    $overwrite = Read-Host "Overwrite? (y/n)"
    if ($overwrite -ne "y") {
        Write-Host "❌ Installation cancelled." -ForegroundColor Red
        exit 0
    }
    # Remove old function
    $profileContent = $profileContent -replace '(?ms)# RLM Method.*?^}', ''
    Set-Content -Path $profilePath -Value $profileContent.TrimEnd()
    Write-Host "✅ Removed old 'rlm' function" -ForegroundColor Green
}

# Add RLM function
$rlmFunction = @"

# RLM Method - Quick launch orchestrator
# Auto-generated by setup-rlm-alias.ps1
function rlm {
    Set-Location "$currentDir"
    copilot --agent rlm-orchestrator
}

"@

Add-Content -Path $profilePath -Value $rlmFunction

Write-Host "`n✅ Successfully installed 'rlm' alias!`n" -ForegroundColor Green
Write-Host "📝 To use it:" -ForegroundColor Cyan
Write-Host "   1. Restart PowerShell (or run: . `$PROFILE)" -ForegroundColor Gray
Write-Host "   2. Navigate to: $currentDir" -ForegroundColor Gray
Write-Host "   3. Type: rlm" -ForegroundColor Gray
Write-Host "   4. You're in orchestrator context!`n" -ForegroundColor Gray

Write-Host "💡 TIP: The 'rlm' function will always return to: $currentDir" -ForegroundColor Yellow
Write-Host "         This ensures the orchestrator has access to RLM artifacts.`n" -ForegroundColor Yellow
