#!/usr/bin/env fish
# RLM Alias Installer for Fish Shell
# Adds 'rlm' alias to Fish config for quick orchestrator access

echo ""
echo "🚀 RLM Alias Installer for Fish Shell"
echo ""

# Get current directory
set CURRENT_DIR (pwd)

# Detect Fish config file
set CONFIG_FILE "$HOME/.config/fish/config.fish"
set CONFIG_DIR (dirname $CONFIG_FILE)

echo "📁 Config file: $CONFIG_FILE"

# Create config directory if doesn't exist
if not test -d $CONFIG_DIR
    mkdir -p $CONFIG_DIR
    echo "✅ Created config directory: $CONFIG_DIR"
end

# Backup existing config
if test -f $CONFIG_FILE
    set BACKUP_FILE "$CONFIG_FILE.backup-"(date +%Y%m%d-%H%M%S)
    cp $CONFIG_FILE $BACKUP_FILE
    echo "✅ Backed up config to: $BACKUP_FILE"
else
    echo "📝 Config file doesn't exist yet. Will create new one."
    touch $CONFIG_FILE
end

# Check if alias exists
if grep -q "alias rlm" $CONFIG_FILE 2>/dev/null
    echo ""
    echo "⚠️  'rlm' alias already exists!"
    read -P "Overwrite? (y/n) " -n 1 -r REPLY
    echo
    if not string match -q -r '^[Yy]$' $REPLY
        echo "❌ Installation cancelled."
        exit 0
    end
    # Remove old alias
    sed -i.tmp '/# RLM Method/,/alias rlm/d' $CONFIG_FILE
    rm -f "$CONFIG_FILE.tmp"
    echo "✅ Removed old 'rlm' alias"
end

# Add RLM alias
echo "

# RLM Method - Quick launch orchestrator
# Auto-generated by setup-rlm-alias.fish
alias rlm='cd \"$CURRENT_DIR\" && copilot --agent rlm-orchestrator'
" >> $CONFIG_FILE

echo ""
echo "✅ Successfully installed 'rlm' alias!"
echo ""
echo "📝 To use it:"
echo "   1. Reload config: source $CONFIG_FILE"
echo "   2. Type: rlm"
echo "   3. You're in orchestrator context!"
echo ""
echo "💡 TIP: The 'rlm' alias will always return to: $CURRENT_DIR"
echo "         This ensures the orchestrator has access to RLM artifacts."
echo ""
