#!/usr/bin/env bash
# RLM Alias Installer for Bash/Zsh
# Adds 'rlm' alias to shell profile for quick orchestrator access

set -e

echo ""
echo "🚀 RLM Alias Installer for Bash/Zsh"
echo ""

# Get current directory
CURRENT_DIR="$(pwd)"

# Detect shell config file
if [[ -n "$ZSH_VERSION" ]]; then
    CONFIG_FILE="$HOME/.zshrc"
    SHELL_NAME="Zsh"
elif [[ -n "$BASH_VERSION" ]]; then
    CONFIG_FILE="$HOME/.bashrc"
    SHELL_NAME="Bash"
else
    echo "❌ Unsupported shell. Use setup-rlm-alias.fish for Fish shell."
    exit 1
fi

echo "📁 Config file: $CONFIG_FILE ($SHELL_NAME)"

# Backup existing config
if [[ -f "$CONFIG_FILE" ]]; then
    BACKUP_FILE="${CONFIG_FILE}.backup-$(date +%Y%m%d-%H%M%S)"
    cp "$CONFIG_FILE" "$BACKUP_FILE"
    echo "✅ Backed up config to: $BACKUP_FILE"
else
    echo "📝 Config file doesn't exist yet. Will create new one."
    touch "$CONFIG_FILE"
fi

# Check if alias exists
if grep -q "alias rlm=" "$CONFIG_FILE" 2>/dev/null; then
    echo ""
    echo "⚠️  'rlm' alias already exists!"
    read -p "Overwrite? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Installation cancelled."
        exit 0
    fi
    # Remove old alias
    sed -i.tmp '/# RLM Method/,/alias rlm=/d' "$CONFIG_FILE"
    rm -f "${CONFIG_FILE}.tmp"
    echo "✅ Removed old 'rlm' alias"
fi

# Add RLM alias
cat >> "$CONFIG_FILE" << EOF

# RLM Method - Quick launch orchestrator
# Auto-generated by setup-rlm-alias.sh
alias rlm='cd "$CURRENT_DIR" && copilot --agent rlm-orchestrator'

EOF

echo ""
echo "✅ Successfully installed 'rlm' alias!"
echo ""
echo "📝 To use it:"
echo "   1. Reload config: source $CONFIG_FILE"
echo "   2. Type: rlm"
echo "   3. You're in orchestrator context!"
echo ""
echo "💡 TIP: The 'rlm' alias will always return to: $CURRENT_DIR"
echo "         This ensures the orchestrator has access to RLM artifacts."
echo ""
